In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
# Read the CSV file into a Pandas DataFrame

districts = pd.read_csv('District_data.csv')
districts = districts.replace('redacted',0)
districts.head()

In [145]:
# Review data types.
districts.dtypes

District               object
County                 object
District_type          object
Enrollment              int64
FRL_Perc              float64
Disadv_Perc           float64
EL_Perc               float64
Grad_Perc             float64
Teach_to_stud         float64
Susp_Perc              object
Chronic_absent         object
Math_metAbove         float64
ELA_metAbove          float64
Per_pupil_exp           int64
Teacher_salary          int64
Avg_years_teaching    float64
dtype: object

In [ ]:
# Rename average years of teaching column.
districts = districts.rename(columns={"Avg Years Teaching (District)": "Avg_years_teaching"})
districts

In [141]:
# Observe means.

Enrollment             6023.941120
FRL_Perc                 56.800965
Disadv_Perc              59.862452
EL_Perc                  18.437052
Grad_Perc                84.543100
Teach_to_stud            20.193016
Math_metAbove            37.324440
ELA_metAbove             48.332442
Per_pupil_exp         14708.595560
Teacher_salary        76081.446911
Avg_years_teaching        9.894221
dtype: float64

In [144]:
### Replace NaaNs with means.
districts = districts.fillna(districts.mean())

,District,County,District_type,Enrollment,FRL_Perc,Disadv_Perc,EL_Perc,Grad_Perc,Teach_to_stud,Susp_Perc,Chronic_absent,Math_metAbove,ELA_metAbove,Per_pupil_exp,Teacher_salary,Avg_years_teaching
0,Happy Camp Union Elementary (Siskiyou),Siskiyou,Elementary School District,110,77.3,77.27,18.437052,84.5431,20.193016,7.9,29.5,9.23,17.91,13585,76081,9.894221
1,Shoreline Unified (Marin),Marin,Unified School District,508,66.9,68.90,42.100000,94.3000,20.193016,3.7,17.7,27.41,43.63,29742,87808,9.894221
2,Cienega Union Elementary (San Benito),San Benito,Elementary School District,25,32.0,44.00,28.000000,84.5431,0.000000,0,6.3,35.00,42.11,11515,76081,9.894221
3,Alpine County Office of Education (Alpine),Alpine,County Office of Education (COE),6023,0.0,0.00,18.437052,84.5431,0.000000,NaN,NaN,37.20,48.30,14708,76081,9.894221
4,Arena Union Elementary/Point Arena Joint Union...,Mendocino,Common Administration District,6023,56.8,60.00,18.400000,84.5431,20.200000,3.5,13.1,37.30,48.30,22151,57730,9.894221
5,Modesto City Schools (Stanislaus),Stanislaus,Common Administration District,6023,56.8,60.00,18.400000,84.5431,20.200000,3.5,13.1,37.30,48.30,13243,93066,9.894221
6,Petaluma City Elementary/Joint Union High (Son...,Sonoma,Common Administration District,6023,56.8,60.00,18.400000,84.5431,20.200000,3.5,13.1,37.30,48.30,12477,72581,9.894221
7,Santa Cruz City Elementary/High (Santa Cruz),Santa Cruz,Common Administration District,6023,56.8,60.00,18.400000,84.5431,20.200000,3.5,13.1,37.30,48.30,14533,77764,9.894221
8,Santa Rosa City Schools (Sonoma),Sonoma,Common Administration District,6023,56.8,60.00,18.400000,84.5431,20.200000,3.5,13.1,37.30,48.30,13576,74869,9.894221
9,SBE - Celerity Rolas (Los Angeles),Los Angeles,State Board of Education Charter,6023,56.8,60.00,18.400000,84.5431,20.200000,3.5,13.1,37.30,48.30,14708,76081,9.894221
10,SBE - Paramount Collegiate Academy (Sacramento),Sacramento,State Board of Education Charter,6023,56.8,60.00,18.400000,84.5431,20.200000,3.5,13.1,37.30,48.30,14708,76081,9.894221
11,SBE - Wei Yu International Charter (Santa Clara),Santa Clara,State Board of Education Charter,6023,56.8,60.00,18.400000,84.5431,20.200000,3.5,13.1,37.30,48.30,14708,76081,9.894221
12,Southside Elementary (San Benito),San Benito,Elementary School District,213,21.6,27.70,16.000000,84.5431,20.193016,2.2,6.8,50.00,68.53,9051,76081,9.894221
13,Knights Ferry Elementary (Stanislaus),Stanislaus,Elementary School District,153,22.2,28.10,7.200000,84.5431,20.193016,2.5,12.4,51.69,51.14,9294,48985,9.894221
14,Magnolia Union Elementary (Imperial),Imperial,Elementary School District,141,17.7,20.57,5.000000,84.5431,20.193016,0,1.4,57.30,63.33,10083,76081,9.894221
15,Elkins Elementary (Tehama),Tehama,Elementary School District,13,92.3,92.31,18.437052,84.5431,13.000000,0,28.6,37.20,48.30,14967,76081,33.000000
16,Montgomery Elementary (Sonoma),Sonoma,Elementary School District,33,45.5,45.45,3.000000,84.5431,11.000000,0,44.1,71.43,50.00,26233,66129,25.000000
17,Klamath River Union Elementary (Siskiyou),Siskiyou,Elementary School District,12,75.0,75.00,18.437052,84.5431,12.000000,7.7,23.1,37.20,48.30,22222,76081,24.000000
18,Sierra County Office of Education (Sierra),Sierra,County Office of Education (COE),6023,0.0,0.00,18.437052,84.5431,0.000000,NaN,NaN,37.20,48.30,14708,76081,21.000000
19,Montebello Unified (Los Angeles),Los Angeles,Unified School District,25409,82.6,87.61,33.200000,80.9000,24.100000,3,13.4,23.88,36.73,13362,97044,18.000000
20,Vista del Mar Union (Santa Barbara),Santa Barbara,Elementary School District,51,39.2,43.14,27.500000,84.5431,10.900000,1.9,21.2,27.27,30.30,30193,76081,18.000000
21,Bitterwater-Tully Elementary (San Benito),San Benito,Elementary School District,35,25.7,34.29,11.400000,84.5431,17.500000,0,7.9,28.00,68.00,10086,76081,18.000000
22,Mountain View Elementary (Los Angeles),Los Angeles,Elementary School District,6346,92.2,95.10,55.500000,84.5431,21.000000,1.8,7.4,28.38,39.57,10609,97079,18.000000
23,Richgrove Elementary (Tulare),Tulare,Elementary School District,589,96.1,97.79,65.500000,84.5431,20.300000,3.8,8.5,13.27,19.80,15801,79595,17.000000
24,El Rancho Unified (Los Angeles),Los Angeles,Unified School District,8472,71.7,74.99,17.700000,91.4000,21.700000,2.9,10.5,28.79,43.34,12467,81373,17.000000
25,Summerville Elementary (Tuolumne),Tuolumne,Elementary School District,409,45.7,45.72,0.200000,84.5431,20.000000,1.6,15.3,32.31,46.39,10788,76081,17.000000
26,Ojai Unified (Ventura),Ventura,Unified School District,2453,50.2,52.70,14.100000,92.0000,22.400000,3.5,10.8,32.68,43.66,11470,67056,17.000000
27,Bassett Unified (Los Angeles),Los Angeles,Unified School District,3520,93.1,94.21,27.500000,96.0000,21.900000,2.7,11,32.81,47.33,13004,82204,17.000000
28,Valle Lindo Elementary (Los Angeles),Los Angeles,Elementary School District,1087,82.3,83.01,9.500000,84.5431,21.300000,1.8,7.1,39.25,52.67,12505,103682,17.000000
29,Buena Park Elementary (Orange),Orange,Elementary School District,4552,68.6,77.27,39.800000,84.5431,22.800000,2.1,6.9,40.25,44.86,13151,92155,17.000000
30,La Mesa-Spring Valley (San Diego),San Diego,Elementary School District,12400,57.7,60.55,18.800000,84.5431,25.500000,4.6,12.7,41.74,52.87,11727,87249,17.000000
31,Magnolia Elementary (Orange),Orange,Elementary School District,5851,83.5,87.75,46.700000,84.5431,23.200000,1.2,8.9,46.76,53.57,11999,93858,17.000000
32,Centralia Elementary (Orange),Orange,Elementary School District,4221,59.4,63.98,23.700000,84.5431,24.700000,0.2,5.5,59.59,63.64,12347,95166,17.000000
33,Franklin Elementary (Sutter),Sutter,Elementary School District,486,25.9,27.57,8.200000,84.5431,23.100000,2.1,5.6,67.76,69.46,9598,80439,17.000000
34,Santa Barbara County Office of Education (Sant...,Santa Barbara,County Office of Education (COE),186,65.1,86.56,40.900000,33.3000,6.800000,3.1,32,0.00,5.45,14708,84359,16.000000
35,South Whittier Elementary (Los Angeles),Los Angeles,Elementary School District,2716,88.3,91.04,41.900000,84.5431,22.500000,2.1,9.2,24.96,36.86,13463,84220,16.000000
36,Dunsmuir Elementary (Siskiyou),Siskiyou,Elementary School District,90,72.2,72.22,18.437052,84.5431,22.500000,2.6,21.8,25.00,26.67,13510,56472,16.000000
37,La Habra City Elementary (Orange),Orange,Elementary School District,4656,74.6,77.63,30.800000,84.5431,22.000000,1.8,6.7,30.56,40.40,12984,93160,16.000000
38,Azusa Unified (Los Angeles),Los Angeles,Unified School District,8010,82.1,85.26,27.000000,90.6000,18.700000,3,9.1,30.73,39.51,14218,87388,16.000000
39,Cuddeback Union Elementary (Humboldt),Humboldt,Elementary School District,149,47.0,46.98,0.700000,84.5431,18.600000,0,5.3,31.33,53.01,10994,53857,16.000000
40,McCloud Union Elementary (Siskiyou),Siskiyou,Elementary School District,60,70.0,70.00,18.437052,84.5431,16.700000,1.5,23.1,35.00,46.51,13035,56825,16.000000
41,Mountain View Elementary (San Bernardino),San Bernardino,Elementary School District,2532,60.4,63.96,15.000000,84.5431,24.500000,1.5,9.6,35.45,52.50,14553,89721,16.000000
42,San Francisco County Office of Education (San ...,San Francisco,County Office of Education (COE),295,53.1,62.87,21.400000,31.5000,10.800000,0.8,50.9,37.20,48.30,14708,76081,16.000000
43,Vallecitos Elementary (San Diego),San Diego,Elementary School District,202,99.5,99.50,48.000000,84.5431,17.000000,0.9,7.3,39.23,54.26,12434,76081,16.000000
44,Downey Unified (Los Angeles),Los Angeles,Unified School District,22064,68.6,71.51,14.900000,96.1000,22.500000,3.4,10.3,41.09,52.71,12831,97043,16.000000
45,Long Beach Unified (Los Angeles),Los Angeles,Unified School District,73221,68.4,70.11,16.900000,87.5000,23.200000,3.6,15.1,45.65,53.92,13154,94044,16.000000
46,Alta-Dutch Flat Union Elementary (Placer),Placer,Elementary School District,99,44.4,44.44,18.437052,84.5431,21.100000,1.8,3.7,46.67,51.67,15317,76081,16.000000
47,Westminster (Orange),Orange,Elementary School District,9120,72.3,76.51,39.800000,84.5431,21.100000,2.8,5.6,51.91,57.94,11711,92836,16.000000
48,Ocean View (Orange),Orange,Elementary School District,7986,46.6,50.16,22.800000,84.5431,23.100000,2.2,6.5,57.55,63.06,11350,91766,16.000000
49,Hope Elementary (Santa Barbara),Santa Barbara,Elementary School District,950,32.1,36.00,16.300000,84.5431,21.900000,0.6,5.2,60.53,69.64,11029,89451,16.000000

In [146]:
# Assign the data to X and y
# Note: Sklearn requires a two-dimensional array of values so we use reshape() to create this

X = districts[["Enrollment","FRL_Perc","Teach_to_stud","Per_pupil_exp","Teacher_salary","Avg_years_teaching"]]
y = districts["ELA_metAbove"]

print("Shape: ", X.shape, y.shape)

Shape:  (1036, 6) (1036,)

In [ ]:
 # Plot the data to find out if a linear trend exists

### BEGIN SOLUTION
plt.scatter(X, y)
plt.xlabel("Teacher Salary")
plt.ylabel("Math Achievement")
### END SOLUTION

In [147]:
 # Use the Sklearn `train_test_split()` function to split the data into training and testing data

from sklearn.model_selection import train_test_split

### BEGIN SOLUTION

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

### END SOLUTION

In [148]:
 # Create the model

### BEGIN SOLUTION

from sklearn.linear_model import LinearRegression

model = LinearRegression()

### END SOLUTION

In [149]:
# Fit the model to the training data. 

### BEGIN SOLUTION

model.fit(X_train, y_train)

### END SOLUTION

LinearRegression()

In [150]:
# Calculate the mean_squared_error and the r-squared value
# for the testing data

from sklearn.metrics import mean_squared_error, r2_score

### BEGIN SOLUTION

# Use our model to make predictions
predicted = model.predict(X_test)

# Score the predictions with mse and r2
mse = mean_squared_error(y_test, predicted)
r2 = r2_score(y_test, predicted)

print(f"mean squared error (MSE): {mse}")
print(f"R-squared (R2): {r2}")

### END SOLUTION

mean squared error (MSE): 108.88437815619356
R-squared (R2): 0.5797436478318847

In [151]:
# Call the `score()` method on the model to show the R2 score

### BEGIN SOLUTION
model.score(X_test, y_test)
### END SOLUTION

0.5797436478318847

In [ ]:
predicted